#!/usr/bin/env bash
# Provision the authorization objects: 1 Developer, 4 API Products, 3 Apps.
# Writes each app's consumerKey/consumerSecret to .secrets.env (git-ignored) for
# the smoke test + Postman. Products are created BEFORE apps (apps subscribe to them).
# Re-runnable: if an app already exists the create returns no key, so it re-reads it.
set -euo pipefail
cd "$(dirname "$0")/.."
set -a; source ./config.env; set +a
TOKEN="$(gcloud auth print-access-token)"
API="https://apigee.googleapis.com/v1/organizations/${ORG}"

# create_product NAME DISPLAY APIRESOURCES_JSON SCOPES_JSON BACKENDS QUOTA_PER_MIN
#   APIRESOURCES_JSON = JSON array of proxy paths this product grants (matched vs proxy.pathsuffix)
#                       "/" = base + all subpaths; "/a" = exactly /a; "/a/**" = subpaths of /a
#   SCOPES_JSON       = JSON array of OAuth scopes this product grants (for bearer tokens)
#   BACKENDS          = comma list of backends (a|b|c) this product may route to (API-key authz)
#   QUOTA_PER_MIN     = requests/min for apps on this product
create_product() {
  local name="$1" disp="$2" res="$3" scopes="$4" backends="$5" quota="$6"
  echo "==> product ${name}  (paths=${res}  scopes=${scopes}  backends=${backends}  quota=${quota}/min)"
  local body
  body="$(jq -n --arg n "$name" --arg d "$disp" --argjson r "$res" --argjson s "$scopes" \
    --arg b "$backends" --arg q "$quota" --arg env "$ENVIRONMENT" --arg px "$PROXY_NAME" \
    '{name:$n, displayName:$d, approvalType:"auto", environments:[$env], proxies:[$px],
      apiResources:$r, scopes:$s, quota:$q, quotaInterval:"1", quotaTimeUnit:"minute",
      attributes:[{name:"backends", value:$b}]}')"
  curl -s -X POST -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" \
    "${API}/apiproducts" -d "$body" | jq -r '.name // .error.message // "(exists)"'
}

# ---- Product ALL: unrestricted (WORKED EXAMPLE showing the create_product call shape) ----
create_product "${PRODUCT_ALL}" "SNI Router - All backends" \
  '["/"]' '["read:a","read:b","read:c"]' "a,b,c" "1000"

# ---- Single-backend products: the authorization matrix ----
# Each grants ONLY its own path (VerifyAPIKey), its own scope (OAuth), and its own
# backend letter (RF-BackendDenied). PRODUCT_A quota=5 so the smoke test trips it.
create_product "${PRODUCT_A}" "SNI Router - Backend A only" \
  '["/a","/a/**"]' '["read:a"]' "a" "5"
create_product "${PRODUCT_B}" "SNI Router - Backend B only" \
  '["/b","/b/**"]' '["read:b"]' "b" "1000"
create_product "${PRODUCT_C}" "SNI Router - Backend C only" \
  '["/c","/c/**"]' '["read:c"]' "c" "1000"

# ---- Developer ----
echo "==> developer ${DEVELOPER_EMAIL}"
curl -s -X POST -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" \
  "${API}/developers" -d "$(jq -n --arg e "$DEVELOPER_EMAIL" --arg f "$DEVELOPER_FIRST" \
    --arg l "$DEVELOPER_LAST" '{email:$e, firstName:$f, lastName:$l, userName:$e}')" \
  | jq -r '.email // .error.message // "(exists)"'

# create_app NAME PRODUCT  -> prints "KEY SECRET"
create_app() {
  local name="$1" prod="$2" resp key secret
  resp="$(curl -s -X POST -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" \
    "${API}/developers/${DEVELOPER_EMAIL}/apps" \
    -d "$(jq -n --arg n "$name" --arg p "$prod" '{name:$n, apiProducts:[$p]}')")"
  key="$(echo "$resp"    | jq -r '.credentials[0].consumerKey // empty')"
  secret="$(echo "$resp" | jq -r '.credentials[0].consumerSecret // empty')"
  if [ -z "$key" ]; then   # already existed -> re-read the app
    resp="$(curl -s -H "Authorization: Bearer ${TOKEN}" "${API}/developers/${DEVELOPER_EMAIL}/apps/${name}")"
    key="$(echo "$resp"    | jq -r '.credentials[0].consumerKey // empty')"
    secret="$(echo "$resp" | jq -r '.credentials[0].consumerSecret // empty')"
  fi
  echo "$key $secret"
}

echo "==> apps + keys"
read -r AKEY ASEC <<< "$(create_app "${APP_A}"   "${PRODUCT_A}")"
read -r BKEY BSEC <<< "$(create_app "${APP_B}"   "${PRODUCT_B}")"
read -r LKEY LSEC <<< "$(create_app "${APP_ALL}" "${PRODUCT_ALL}")"

cat > .secrets.env <<EOF
# Generated by scripts/20-create-authz.sh — DO NOT COMMIT (see .gitignore)
export APP_A_KEY="${AKEY}"
export APP_A_SECRET="${ASEC}"
export APP_B_KEY="${BKEY}"
export APP_B_SECRET="${BSEC}"
export APP_ALL_KEY="${LKEY}"
export APP_ALL_SECRET="${LSEC}"
EOF
chmod 600 .secrets.env

echo
echo "==> Wrote .secrets.env (keys hidden):"
sed -E 's/=".*"/=<set>/' .secrets.env | grep KEY
echo
echo "Next: scripts/30-smoke.sh   (and paste these keys into postman/sni-router.postman_environment.json for Postman)"
